# Numpy Tutorial

In [ ]:
import numpy as np

Numpy is a library for computations of multi-dimensional arrays. It comes with a large collection of functions for mathematical operations on these arrays.

In the above, we have "import numpy as np", which means that we have imported the numpy library and set "np" as the abbreviation for calling numpy.

In [ ]:
## Define single value numerical variables in Python
a = 1
b = 5
c = a + b
print(c)

6


In [ ]:
# You can put these numbers into lists
A = [2,3]
B = [3,5]

# However, lists do not allow for mathematical operations
C = A + B    # For example, + operator on two lists is concatenation, not elementwise addition
print('C: ', C)
print(type(C))

C:  [2, 3, 3, 5]
<class 'list'>


### Numpy Array
- Numpy library enable us to perform mathematical operations on arrays

In [ ]:
# np.array() converts list into numpy array
A = np.array(A)
print('A: ', A)
B = np.array(B)
C = A + B
print('C: ', C)
print(type(C))
print(C.shape)   # C is a 2-dim vector

A:  [2 3]
C:  [5 8]
<class 'numpy.ndarray'>
(2,)


In [ ]:
# How to concatenate
temp = np.concatenate([A,B], axis=0)
print (temp)
temp = np.concatenate([[A],[B]], axis=0)
print (temp)


[2 3 3 5]
[[2 3]
 [3 5]]


In [ ]:
D = np.array([[1,2],[3,4]])
print('D: \n', D)
print('D.shape: ', D.shape)   ## D is a 2x2 matrix
E = np.random.randn(2,1)    # Creates a 2x1 matrix with gaussian random elements
print('E: \n', E)

print('D*E: \n', D*E)   
# Note that this is not a standard matrix multiplication, but an elementwise multiplication
# np broadcasts E to fit size of D and perform elementwise multiplication

# Matrix multiplication
print('np.matmul(D,E): \n', np.matmul(D,E)) 

D: 
 [[1 2]
 [3 4]]
D.shape:  (2, 2)
E: 
 [[ 1.18072706]
 [-0.80944608]]
D*E: 
 [[ 1.18072706  2.36145412]
 [-2.42833824 -3.23778431]]
np.matmul(D,E): 
 [[-0.4381651 ]
 [ 0.30439687]]


### Array indexing and reshaping

In [ ]:
# Index for np array starts at 0 
# For a 2D array, the first index is for row, second index is for column
H = np.random.randint(0,10,(5,5))
print('H: ')
print(H)
print('H[0,0]:', H[0,0])    # Element in row 0, column 0
print('H[1,2]:', H[1,2])    # Element in row 1, column 2
print('H[-1,-1]:', H[-1,-1])   # Element in last row, last column

H: 
[[2 3 0 1 8]
 [8 8 9 2 8]
 [0 1 3 9 6]
 [4 3 8 3 1]
 [4 7 4 3 0]]
H[0,0]: 2
H[1,2]: 9
H[-1,-1]: 0


In [ ]:
# Use a:b to extract elements from a to b-1
r = H[0,1:3]   ## Extract the row index 0, col index 1,2
print('r: ', r)
print(r.shape)

r:  [3 0]
(2,)


In [ ]:
r = H[2,:]   ## Extract the entire row 3 of H
print('r: ', r)
print(r.shape)
## Note that the extracted row is not a (1,5) array (has 2 dimensions) but a (5,) array (only 1 dimension)
## Be aware of this change in shape when indexing

## You can reshape r to (1,5)
r = r.reshape(1,5)
print(r)
print(r.shape)

r:  [0 1 3 9 6]
(5,)
[[0 1 3 9 6]]
(1, 5)


### Some useful numpy functions

In [ ]:
print(np.trace(H))   # Calculate the trace (sum of diagonal elements)
print(np.mean(H))    # Calculate the arithmetic mean of all elements in H
print(np.mean(H, axis = 0))   # Calculate the mean across the axis 0
print(np.linalg.inv(H))    # Find the inverse matrix
print(np.transpose(H))     # Take the transpose of the matrix

16
4.2
[3.6 4.4 4.8 3.6 4.6]
[[-4.13212435  3.67098446  1.31865285 -4.22279793 -0.80310881]
 [ 1.88082902 -1.63989637 -0.62435233  1.81865285  0.52072539]
 [ 1.73056995 -1.53367876 -0.58549223  1.93782383  0.2642487 ]
 [-1.1865285   0.97668394  0.47927461 -1.19689119 -0.16321244]
 [ 0.60103627 -0.42487047 -0.15544041  0.52331606  0.02590674]]
[[2 8 0 4 4]
 [3 8 1 3 7]
 [0 9 3 8 4]
 [1 2 9 3 3]
 [8 8 6 1 0]]


In [ ]:
np.matmul(H, np.linalg.inv(H))

array([[ 1.00000000e+00,  8.88178420e-16, -2.22044605e-16,
         8.88178420e-16,  1.38777878e-16],
       [ 0.00000000e+00,  1.00000000e+00, -8.88178420e-16,
         2.66453526e-15,  3.05311332e-16],
       [ 1.55431223e-15, -2.33146835e-15,  1.00000000e+00,
         1.11022302e-15,  4.64905892e-16],
       [ 1.66533454e-15, -5.55111512e-17, -9.43689571e-16,
         1.00000000e+00,  2.81025203e-16],
       [-2.22044605e-16,  1.66533454e-15, -5.55111512e-16,
         2.22044605e-15,  1.00000000e+00]])

### Fancy Index

In [ ]:
mapping = np.random.permutation(10)
print (mapping)

[7 9 2 0 6 3 1 8 5 4]


In [ ]:
mat = np.random.randint(0,10,(3,3))
print (mat)

[[7 2 4]
 [2 8 3]
 [2 6 0]]


In [ ]:
mapping[mat]

array([[8, 2, 6],
       [2, 5, 0],
       [2, 1, 7]])